module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'chore',
        'game',
        'editor',
        'data',
        'server',
        'infra',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'scenes',
        'entities',
        'systems',
        'ui',
        'assets',
        'components',
        'api',
        'cdk',
        'build',
        'ci',
        'deps',
        'config',
      ],
    ],
    'subject-case': [2, 'never', ['sentence-case', 'start-case', 'pascal-case', 'upper-case']],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'type-case': [2, 'always', 'lower-case'],
    'type-empty': [2, 'never'],
  },
};
